export const ADD_FILM = 'ADD_FILM';
export const REMOVE_FILM = 'REMOVE_FILM';
export const SET_FILMS = 'SET_FILMS';
export const FETCH_FILMS_FAILED = 'FETCH_FILMS_FAILED';

export const PURCHASE_FILMCASE_START = 'PURCHASE_FILMCASE_START';
export const PURCHASE_FILMCASE_SUCCESS = 'PURCHASE_FILMCASE_SUCCESS';
export const PURCHASE_FILMCASE_FAIL = 'PURCHASE_FILMCASE_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
